/*
 * Payments
 * Enable your customers to make intrabank or IBFT payments through our payment APIs.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Ignore
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    
    /**
     * Make Payments
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void initiateWalletPaymentTest() {
        Integer walletId = null;
        String xNeemId = null;
        Integer xNeemPartnerId = null;
        Object body = null;
        Object response = api.initiateWalletPayment(walletId, xNeemId, xNeemPartnerId, body);

        // TODO: test validations
    }
    
    /**
     * Bill Inquiry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void walletBillInquiryTest() {
        String walletId = null;
        String xNeemId = null;
        Integer xNeemPartnerId = null;
        String endToEndIdentification = null;
        String productId = null;
        String consumerNumber = null;
        Object response = api.walletBillInquiry(walletId, xNeemId, xNeemPartnerId, endToEndIdentification, productId, consumerNumber);

        // TODO: test validations
    }
    
    /**
     * Bill Payment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void walletBillPaymentTest() {
        Integer walletId = null;
        String xNeemId = null;
        Integer xNeemPartnerId = null;
        Object body = null;
        Object response = api.walletBillPayment(walletId, xNeemId, xNeemPartnerId, body);

        // TODO: test validations
    }
    
    /**
     * Payment Inquiry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void walletPaymentInquiryTest() {
        String walletId = null;
        String xNeemId = null;
        Integer xNeemPartnerId = null;
        String endToEndIdentification = null;
        String paymentScheme = null;
        String amount = null;
        String currency = null;
        String creditorIdentification = null;
        String creditorName = null;
        String creditorInstitutionIdentification = null;
        String creditorSecondaryIdentification = null;
        List<Object> extendedProperties = null;
        Object response = api.walletPaymentInquiry(walletId, xNeemId, xNeemPartnerId, endToEndIdentification, paymentScheme, amount, currency, creditorIdentification, creditorName, creditorInstitutionIdentification, creditorSecondaryIdentification, extendedProperties);

        // TODO: test validations
    }
    
}
